buildscript {
    repositories {
        google()
        mavenCentral()
    }
    dependencies {
        // Use a versão 8.2.2 que é estável com o SDK 34 e Java 17
        classpath 'com.android.tools.build:gradle:8.2.2'
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:1.9.0"
    }
}

allprojects {
    repositories {
        google()
        mavenCentral()
    }
}
